---
title: "Mimosoid Phylodiversity"
author: "Michael W Belitz"
date: '2022-09-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(terra)
library(sf)
library(ggplot2)
library(dplyr)

world <- rnaturalearth::ne_countries(returnclass = "sf") %>% 
  st_transform("+proj=moll +lon_0=1 +datum=WGS84 +units=m +no_defs")
```

## Richness

```{r rich, echo=FALSE}
rich <- rast("mimosoidBiodiverse/spatial__CHAO2_ESTIMATE.tif")
rich <- rich %>% 
  terra::as.data.frame(xy = T) %>% 
  dplyr::rename(richness = 3)
  
ggplot() +
  geom_sf(world, mapping = aes(), fill = NA) + 
  geom_tile(rich, mapping = aes(x = x, y = y, fill = richness)) +
  coord_sf(xlim = c(min(rich$x, na.rm = T) - 500000, max(rich$x, na.rm = T) + 500000),
          ylim = c(min(rich$y, na.rm = T) - 500000, max(rich$y, na.rm = T) + 5000)) +
  scale_fill_viridis_c(option = "mako") +
  theme_void()

```

## PD_P

```{r pd, echo=FALSE}
pd <- rast("mimosoidBiodiverse/spatial__PD_P.tif") %>% 
  terra::as.data.frame(xy = T) %>% 
  dplyr::rename(pd_p = 3)
  
ggplot() +
  geom_sf(world, mapping = aes(), fill = NA) + 
  geom_tile(pd, mapping = aes(x = x, y = y, fill = pd_p)) +
  coord_sf(xlim = c(min(pd$x, na.rm = T) - 500000, max(pd$x, na.rm = T) + 500000),
          ylim = c(min(pd$y, na.rm = T) - 500000, max(pd$y, na.rm = T) + 5000)) +
  scale_fill_viridis_c() +
  theme_void()

```

## RPD

```{r rpd, echo=FALSE}
rpd <- rast("mimosoidBiodiverse/spatial__PHYLO_RPD2.tif") %>% 
  terra::as.data.frame(xy = T) %>% 
  dplyr::rename(rpd = 3)
  
ggplot() +
  geom_sf(world, mapping = aes(), fill = NA) + 
  geom_tile(rpd, mapping = aes(x = x, y = y, fill = rpd)) +
  coord_sf(xlim = c(min(rpd$x, na.rm = T) - 500000, max(rpd$x, na.rm = T) + 500000),
          ylim = c(min(rpd$y, na.rm = T) - 500000, max(rpd$y, na.rm = T) + 5000)) +
  scale_fill_viridis_c() +
  theme_void()

```

## PE_CWE

```{r cwe, echo=FALSE}
cwe <- rast("mimosoidBiodiverse/spatial__PE_CWE.tif") %>% 
  terra::as.data.frame(xy = T) %>% 
  dplyr::rename(pe_cwe = 3)
  
ggplot() +
  geom_sf(world, mapping = aes(), fill = NA) + 
  geom_tile(cwe, mapping = aes(x = x, y = y, fill = pe_cwe)) +
  coord_sf(xlim = c(min(cwe$x, na.rm = T) - 500000, max(cwe$x, na.rm = T) + 500000),
          ylim = c(min(cwe$y, na.rm = T) - 500000, max(cwe$y, na.rm = T) + 5000)) +
  scale_fill_viridis_c(trans = "log", option = "turbo") +
  theme_void()

```


## PMPD
Phylogenetic mean pairwise distance

```{r pmpd, echo=FALSE}
pmpd <- rast("mimosoidBiodiverse/spatial__PMPD2_MEAN.tif") %>% 
  terra::as.data.frame(xy = T) %>% 
  dplyr::rename(pmpd = 3)
  
ggplot() +
  geom_sf(world, mapping = aes(), fill = NA) + 
  geom_tile(pmpd, mapping = aes(x = x, y = y, fill = pmpd)) +
  coord_sf(xlim = c(min(pmpd$x, na.rm = T) - 500000, max(pmpd$x, na.rm = T) + 500000),
          ylim = c(min(pmpd$y, na.rm = T) - 500000, max(pmpd$y, na.rm = T) + 5000)) +
  scale_fill_viridis_c(option = "turbo") +
  theme_void()

```


# Randomizations

## PD_P randomization

```{r pd_rand, echo=FALSE}
pd <- rast("mimosoidBiodiverse/rand__PD_P.tif") %>% 
  terra::as.data.frame(xy = T) %>% 
  dplyr::rename(Sig = 3) %>% 
  mutate(Sig = case_when(Sig <= 0.05 ~ "Low",
                                  Sig >= 0.95 ~ "High")) %>% 
  filter(!is.na(Sig)) 
  
ggplot() +
  geom_sf(world, mapping = aes(), fill = NA) + 
  geom_tile(pd, mapping = aes(x = x, y = y, fill = Sig)) +
  coord_sf(xlim = c(min(pd$x, na.rm = T) - 500000, max(pd$x, na.rm = T) + 500000),
          ylim = c(min(pd$y, na.rm = T) - 500000, max(pd$y, na.rm = T) + 5000)) +
  scale_fill_manual(values = c("dodgerblue2", "red1")) +
  theme_void()

```


## RPD randomization

```{r rpd_rand, echo=FALSE}
rpd <- rast("mimosoidBiodiverse/rand__PHYLO_RPD2.tif") %>% 
  terra::as.data.frame(xy = T) %>% 
  dplyr::rename(Sig = 3) %>% 
  mutate(Sig = case_when(Sig <= 0.05 ~ "Low",
                                  Sig >= 0.95 ~ "High")) %>% 
  filter(!is.na(Sig)) 
  
ggplot() +
  geom_sf(world, mapping = aes(), fill = NA) + 
  geom_tile(rpd, mapping = aes(x = x, y = y, fill = Sig)) +
  coord_sf(xlim = c(min(rpd$x, na.rm = T) - 500000, max(rpd$x, na.rm = T) + 500000),
          ylim = c(min(rpd$y, na.rm = T) - 500000, max(rpd$y, na.rm = T) + 5000)) +
  scale_fill_manual(values = c("dodgerblue2", "red1")) +
  theme_void()

```


## CANAPE

```{r canape, echo=F, fig.width=8, fig.height=2.5, message=F, warning=FALSE}
xx <- rast("mimosoidBiodiverse/rand__PE_CWE.tif")
xx_df <- terra::as.data.frame(xx, xy = TRUE) %>% 
  dplyr::rename(PE_WE_P = 3)

yy <- rast("mimosoidBiodiverse/rand__PHYLO_RPE_NULL2.tif")
yy_df <- terra::as.data.frame(yy, xy = TRUE) %>% 
  dplyr::rename(RPE_NULL2 = 3)

zz <- rast("mimosoidBiodiverse/rand__PHYLO_RPE2.tif")
zz_df <- terra::as.data.frame(zz, xy = TRUE) %>% 
  dplyr::rename(RPE2 = 3)


significance_fun <- function(x, y, z){
  #  simplify the logic below
  ifelse(test = is.na(x), yes = 0, no = x)
  ifelse(test = is.na(y), yes = 0, no = x)
  ifelse(test = is.na(z), yes = 0.5, no = x)
  
  ifelse(test = x <= 0.95 & y <= 0.95, yes = "Not Sig",
         no = 
           ifelse(z < 0.025, yes = "Neo",
                  no = 
                    ifelse(z > 0.975, yes = "Paleo",
                           no = "Mixed")
           ))
}

Significance <- significance_fun(x = xx_df$PE_WE_P, 
                                 y = yy_df$RPE_NULL2, 
                                 z = zz_df$RPE2)

df2 <- left_join(xx_df, yy_df) 
df2 <- left_join(df2, zz_df)

df3 <- df2 %>% 
  mutate(PE_WE_P = tidyr::replace_na(PE_WE_P, 0),
         RPE_NULL2 = tidyr::replace_na(RPE_NULL2, 0),
         RPE2 = tidyr::replace_na(RPE2, 0.5)) 

Significance <- significance_fun(x = df3$PE_WE_P, y = df3$RPE_NULL2,
                                 z = df3$RPE2)

canape_csv <- cbind(df3, Significance) %>% 
  dplyr::select(x, y, Significance)


ggplot() + 
  geom_sf(world, mapping = aes(), fill = NA, color = "grey25") +
  geom_tile(canape_csv, mapping = aes(x = x, y = y, fill = Significance)) + 
  scale_fill_manual(values = c("#CB7FFF", "red", "transparent", "royalblue1")) +
    coord_sf(xlim = c(min(canape_csv$x, na.rm = T) - 500000, max(canape_csv$x, na.rm = T) + 500000),
          ylim = c(min(canape_csv$y, na.rm = T) - 500000, max(canape_csv$y, na.rm = T) + 5000)) +
  theme_void()
```


## Proportion nodulating

```{r prop_nod, echo=FALSE}
library(sp)
# read in nodulating data
nod <- data.table::fread("./../mimosoid_nodulationstatus_persepecies.csv", header = T)

# read in sdm data
sdm <- data.table::fread("./../Mimosoid_SDMs_AsCSV_20KM_presencesOnly.csv") 

sdm_nod <- left_join(sdm, nod, by = c("binomial" = "species"))

rich <- raster::raster("mimosoidBiodiverse/spatial__CHAO2_ESTIMATE.tif")

sp_df <- sdm_nod
coordinates(sp_df) <- ~ x_reg + y_reg

# regularlize coordinates
biomdf <- raster::as.data.frame(rich, xy = T)
biomdf_noNA <- na.omit(biomdf) %>%
  dplyr::rename(z = 3)
biomdf_noNA <- mutate(biomdf_noNA, z = 1:nrow(biomdf_noNA))
bio_2 <- raster::rasterFromXYZ(biomdf_noNA)

e <- raster::extract(bio_2, sp_df)
sp_df$cell_id <- e

tbl_fread2 <- base::as.data.frame(sp_df)
sdm_nod2 <- na.omit(tbl_fread2)

sdm_nod2_reg <- left_join(sdm_nod2, biomdf_noNA, by = c("cell_id" = "z"))

nod_sum <- sdm_nod2_reg %>% 
  group_by(x, y) %>% 
  summarise(prop_nod = sum(nodulation == "Yes", na.rm = T) / n(), 
            richness = n())

ggplot() +
  geom_sf(world, mapping = aes(), fill = NA, color = "grey25") +
  geom_tile(filter(nod_sum, richness > 2), mapping = aes(x = x, y = y, fill = prop_nod)) +
  coord_sf(xlim = c(min(nod_sum$x, na.rm = T) - 500000, max(nod_sum$x, na.rm = T) + 500000),
          ylim = c(min(nod_sum$y, na.rm = T) - 500000, max(nod_sum$y, na.rm = T) + 5000)) +
  scale_fill_viridis_c() +
  theme_void()

```